### ISSUE TITLE
Cuurent status

### ISSUE THREAD

**Issue by ThatAIGeek** [renatoGarcia/gdb-imshow#1]
Hi there! Just wondering what is the current state of this extension and if there is a plugin for qt creator that can do the same thing?

**Comment by renatoGarcia** [comment]
Hi Liberus. I have just tested this with Python 3.6.1, GDB 7.12.1, and OpenCV 3.2.0. All worked.

About Qt Creator, I don't use it myself, but if I remember correctly you can open a GDB terminal inside it when debugging, and this plugin must work from there.

**Comment by ThatAIGeek** [comment]
Thanks!

I was looking for smth like imagewatch for VS in Qt Creator, but looks like your project is the way to go solution for now.(
Thanks anyway!
